### ISSUE TITLE
Remove pkg/util

### ISSUE THREAD

**Issue by hasheddan** [crossplaneio/crossplane-runtime#1]
This issue has been created to track the work originally expressed in crossplaneio/crossplane#448

It's generally considered a mispattern in the Go world to create package names like `util`, or `common`. The preferred alternatives are typically one or more of:
* Breaking out functions into targeted packages with self documenting names like `strings`, `metadata`, etc.
* Tolerating the existence of duplicate instances of simple utility functions like `util.ToLowerRemoveSpaces` defined closer to where they're used.
* Avoiding such extremely simple utility functions altogether.

Sources:
* https://blog.golang.org/package-names (See "Bad package names")
* https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
* https://rakyll.org/style-packages/

**Comment by negz** [comment]
As of https://github.com/crossplaneio/crossplane-runtime/pull/112 we're down to two functions left in `pkg/util`:

* `GeneratePassword`  is used by a handful of cache and database managed resource controllers, and the latter is used by all bucket controllers. We might consider replacing it with https://godoc.org/github.com/sethvargo/go-password/password#MustGenerate
* `ConditionalStringFormat` is used by the bucket controllers. I believe it's only used to set bucket names, and should thus be replaced by the `crossplaneio/external-name` annotation once we bump those controllers to the crossplane-runtime managed resource reconciler.
